Add code showing ndk-build failure
Before showing the error, let's explain what happens. Basically on the
platforms that fail Android uses libc++ with gabi++ rather than using
libc++abi. Unfortunately, __cxa_demangle() is not defined by gabi++ as
it ought to be. Hence the following failures:

    $ ~/Android/android-ndk-r10d/ndk-build -k
    [arm64-v8a] Compile++      : main <= main.cpp
    [arm64-v8a] StaticLibrary  : libmain.a
    [x86_64] Compile++      : main <= main.cpp
    In file included from jni/main.cpp:1:
    boost_core/include/boost/core/demangle.hpp:75:17: error: no member named
          '__cxa_demangle' in namespace '__cxxabiv1'
        return abi::__cxa_demangle( name, NULL, &size, &status );
               ~~~~~^
    1 error generated.
    make: *** [obj/local/x86_64/objs/main/main.o] Error 1
    [mips64] Compile++      : main <= main.cpp
    In file included from jni/main.cpp:1:
    boost_core/include/boost/core/demangle.hpp:75:17: error: no member named '__cxa_demangle' in namespace '__cxxabiv1'
        return abi::__cxa_demangle( name, NULL, &size, &status );
               ~~~~~^
    1 error generated.
    make: *** [obj/local/mips64/objs/main/main.o] Error 1
    [armeabi-v7a] Compile++ thumb: main <= main.cpp
    [armeabi-v7a] StaticLibrary  : libmain.a
    [armeabi] Compile++ thumb: main <= main.cpp
    [armeabi] StaticLibrary  : libmain.a
    [x86] Compile++      : main <= main.cpp
    In file included from jni/main.cpp:1:
    boost_core/include/boost/core/demangle.hpp:75:17: error: no member named
          '__cxa_demangle' in namespace '__cxxabiv1'
        return abi::__cxa_demangle( name, NULL, &size, &status );
               ~~~~~^
    1 error generated.
    make: *** [obj/local/x86/objs/main/main.o] Error 1
    [mips] Compile++      : main <= main.cpp
    In file included from jni/main.cpp:1:
    boost_core/include/boost/core/demangle.hpp:75:17: error: no member named '__cxa_demangle' in namespace '__cxxabiv1'
        return abi::__cxa_demangle( name, NULL, &size, &status );
               ~~~~~^
    1 error generated.
    make: *** [obj/local/mips/objs/main/main.o] Error 1
    make: Target `all' not remade because of errors.

Note that the master branch of boost_core points to the current HEAD
of boostorg/core as of this writing.